# Generated by Django 2.2.24 on 2024-06-16 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('massaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='messages/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
