# Generated by Django 2.2.24 on 2024-06-19 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('massaging', '0002_auto_20240616_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='file',
        ),
    ]
