# Generated by Django 2.2.24 on 2024-06-21 19:24

import Sumsal_Backend.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('massaging', '0003_remove_message_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=Sumsal_Backend.storage_backends.ImagenText(), upload_to=''),
        ),
        migrations.AddField(
            model_name='message',
            name='video',
            field=models.FileField(blank=True, null=True, storage=Sumsal_Backend.storage_backends.VideoStorage(), upload_to=''),
        ),
    ]
