# Generated by Django 2.2.24 on 2024-07-12 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('massaging', '0008_auto_20240624_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='translated_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
