# Generated by Django 4.2.25 on 2025-12-05 07:13

import Sumsal_Backend.storage_backends
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('massaging', '0009_message_translated_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=Sumsal_Backend.storage_backends.VideoStorage(), upload_to='messages/attachments/')),
                ('file_type', models.CharField(blank=True, max_length=100)),
                ('is_image', models.BooleanField(default=False)),
                ('is_video', models.BooleanField(default=False)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='massaging.message')),
            ],
        ),
        migrations.CreateModel(
            name='GroupMessageAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=Sumsal_Backend.storage_backends.VideoStorage(), upload_to='group_messages/attachments/')),
                ('file_type', models.CharField(blank=True, max_length=100)),
                ('is_image', models.BooleanField(default=False)),
                ('is_video', models.BooleanField(default=False)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='massaging.groupmessage')),
            ],
        ),
    ]
