# Generated by Django 4.2.25 on 2025-12-14 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('massaging', '0010_messageattachment_groupmessageattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='replied_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='massaging.groupmessage'),
        ),
        migrations.AddField(
            model_name='message',
            name='replied_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='massaging.message'),
        ),
    ]
