# Generated by Django 6.0 on 2026-08-15 10:14

from django.conf import settings
from django.db import migrations, models


def deduplicate_group_memberships(apps, schema_editor):
    GroupMembership = apps.get_model("massaging", "GroupMembership")
    duplicates = (
        GroupMembership.objects.values("user_id", "group_id")
        .annotate(total=models.Count("id"))
        .filter(total__gt=1)
    )
    for duplicate in duplicates.iterator():
        memberships = GroupMembership.objects.filter(
            user_id=duplicate["user_id"],
            group_id=duplicate["group_id"],
        ).order_by("joined_at", "id")
        keeper = memberships.first()
        if memberships.filter(is_admin=True).exists() and not keeper.is_admin:
            keeper.is_admin = True
            keeper.save(update_fields=["is_admin"])
        memberships.exclude(id=keeper.id).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('massaging', '0012_alter_group_id_alter_groupmembership_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmembership',
            name='last_read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(
            deduplicate_group_memberships,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='groupmembership',
            constraint=models.UniqueConstraint(fields=('user', 'group'), name='unique_group_membership'),
        ),
    ]
