# Generated by Django 6.0 on 2026-07-25 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="interaction_score",
            field=models.IntegerField(default=0, help_text="Score for feed ranking"),
        ),
    ]
