# Generated by Django 6.0 on 2026-04-29 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_newpeticioncommentpost_post"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubFactores",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=1000)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="subfactores/images/"
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True, null=True, upload_to="subfactores/videos/"
                    ),
                ),
                ("link", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent_task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subfactores",
                        to="api.task",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubFactoresCommentPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=1000)),
                ("description", models.TextField(blank=True, default="")),
                ("link", models.TextField(blank=True, default="")),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="comments/subfactores/images/"
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True, null=True, upload_to="comments/subfactores/videos/"
                    ),
                ),
                (
                    "parent_task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subfactores",
                        to="api.newpeticioncommentpost",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubFuentes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=1000)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="subfuentes/images/"
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True, null=True, upload_to="subfuentes/videos/"
                    ),
                ),
                ("link", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent_task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subfuentes",
                        to="api.task",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubFuentesCommentPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=1000)),
                ("description", models.TextField(blank=True, default="")),
                ("link", models.TextField(blank=True, default="")),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="comments/subfuentes/images/"
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True, null=True, upload_to="comments/subfuentes/videos/"
                    ),
                ),
                (
                    "parent_task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subfuentes",
                        to="api.newpeticioncommentpost",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=1000)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="subtasks/images/"
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True, null=True, upload_to="subtasks/videos/"
                    ),
                ),
                ("link", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent_task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subtasks",
                        to="api.task",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubTaskCommentPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=1000)),
                ("description", models.TextField(blank=True, default="")),
                ("link", models.TextField(blank=True, default="")),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="comments/subtasks/images/"
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True, null=True, upload_to="comments/subtasks/videos/"
                    ),
                ),
                (
                    "parent_task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subtasks",
                        to="api.newpeticioncommentpost",
                    ),
                ),
            ],
        ),
    ]
