# Generated by Django 5.1.14 on 2026-05-08 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postt",
            name="title",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
