# Generated by Django 5.1.14 on 2026-05-09 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_postt_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postt",
            name="title",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
