# Generated by Django 6.0 on 2026-09-06 01:08

from django.db import migrations, models


def seed_podcast_category(apps, schema_editor):
    """Crea la categoría 'Grabar Podcast' exclusiva de peticiones (idempotente)."""
    NewCategory = apps.get_model("api", "NewCategory")
    if not NewCategory.objects.filter(name__iexact="Grabar Podcast").exists():
        NewCategory.objects.create(name="Grabar Podcast", pch="peticiones")


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_tasktag"),
    ]

    operations = [
        migrations.AddField(
            model_name="newcategory",
            name="pch",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Tipo de aportación dueño de esta categoría (consejos/peticiones/historias)",
                max_length=20,
                verbose_name="pch",
            ),
        ),
        migrations.RunPython(seed_podcast_category, migrations.RunPython.noop),
    ]
