# Generated by Django 6.0 on 2026-07-08 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_sharedtaskcomment_likesharedtask_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="likep",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="api.profile",
            ),
        ),
    ]
