# Generated by Django 6.0 on 2026-07-14 22:11
# Neutralized: the live database is still on numeric task identifiers, so
# applying a UUID-only schema change here causes the migration to fail.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_likep_profile'),
    ]

    operations = []
