# Generated by Django 6.0 on 2026-09-06 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_newcategory_pch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newcategory",
            name="name",
            field=models.CharField(max_length=100, verbose_name="name"),
        ),
        migrations.AlterUniqueTogether(
            name="newcategory",
            unique_together={("name", "pch")},
        ),
    ]
