# Generated by Django 6.0 on 2026-09-08 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_usersavedfilter"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="categoryp",
            options={"ordering": ["position", "created_at"]},
        ),
        migrations.AddField(
            model_name="categoryp",
            name="position",
            field=models.PositiveIntegerField(default=0, verbose_name="position"),
        ),
    ]
