# Generated by Django 6.0 on 2026-09-09 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_alter_categoryp_options_categoryp_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="personal_filter_public",
            field=models.BooleanField(
                default=False, verbose_name="personal filter public"
            ),
        ),
    ]
