# Generated by Django 6.0 on 2026-09-12 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_profile_personal_filter_public"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="categoryp",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="categoryp",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="api.categoryp",
            ),
        ),
        migrations.AddField(
            model_name="newcategory",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="api.newcategory",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="personal_filter_public",
            field=models.BooleanField(
                default=False, verbose_name="show personal filter everywhere"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="categoryp",
            unique_together={("user", "name", "parent")},
        ),
    ]
