# Generated by Django 6.0 on 2026-10-02 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_favorites_order_visibility"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="postt",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="sharedtask",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddIndex(
            model_name="favorito",
            index=models.Index(
                fields=["user", "-created_at"], name="favorito_user_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="favorito",
            index=models.Index(
                fields=["user", "is_pinned", "position"], name="favorito_user_pin_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="newpeticioncommentpost",
            index=models.Index(
                fields=["post", "parent", "-created_at"], name="comment_post_parent_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="postt",
            index=models.Index(
                fields=["parent", "-created_at"], name="postt_parent_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="postt",
            index=models.Index(
                fields=["user", "-created_at"], name="postt_user_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sharedtask",
            index=models.Index(fields=["-created_at"], name="sharedtask_date_idx"),
        ),
        migrations.AddIndex(
            model_name="sharedtask",
            index=models.Index(
                fields=["task", "-created_at"], name="sharedtask_task_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sharedtask",
            index=models.Index(
                fields=["shared_by", "-created_at"], name="sharedtask_by_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sharedtaskcomment",
            index=models.Index(
                fields=["shared_task", "parent", "-created_at"],
                name="stcomment_task_parent_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["pch", "-created_at"], name="task_pch_date_idx"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["user", "-created_at"], name="task_user_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["pch", "user"], name="task_pch_user_idx"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["-interaction_score", "-created_at"], name="task_score_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["pch", "story_is_shared"], name="task_pch_shared_idx"
            ),
        ),
    ]
