"""
Django settings for Sumsal_Backend project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import sys
import dj_database_url
from pathlib import Path
from datetime import timedelta
from urllib.parse import urlparse
from django.utils.translation import gettext_lazy as _
from django.core.exceptions import ImproperlyConfigured

# ─── Sentry (crash reporting) ─────────────────────────────────────────────────
# Activa solo si SENTRY_DSN está definido en el entorno.
# En local sin DSN, esta sección no tiene efecto.
_SENTRY_DSN = os.getenv("SENTRY_DSN", "")
if _SENTRY_DSN:
    import sentry_sdk
    from sentry_sdk.integrations.django import DjangoIntegration
    sentry_sdk.init(
        dsn=_SENTRY_DSN,
        integrations=[DjangoIntegration()],
        # Captura 10% de las transacciones para performance tracing
        traces_sample_rate=0.1,
        # No enviar datos personales (emails, IPs) a Sentry
        send_default_pii=False,
    )

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG") == "True"

ALLOWED_HOSTS = (
    os.getenv("DJANGO_ALLOWED_HOSTS").split(",")
    if os.getenv("DJANGO_ALLOWED_HOSTS")
    else []
)

CSRF_TRUSTED_ORIGINS = (
    os.getenv("DJANGO_CSRF_TRUSTED_ORIGINS").split(",")
    if os.getenv("DJANGO_CSRF_TRUSTED_ORIGINS")
    else []
)

# CORS settings
CORS_ORIGIN_ALLOW_ALL = True

# Application definition
INSTALLED_APPS = [
    "api",  # Must be first to ensure User model is available for auth
    "corsheaders",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",  # Lista negra de tokens invalidados
    # Temporarily disabled for migration
    # "forum",
    "massaging",
    # "newforum",
    # "newpeticiones",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    # "django.middleware.locale.LocaleMiddleware", # ⚡ Desactivado para evitar que inyecte /en/ en la API
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "Sumsal_Backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "Sumsal_Backend.wsgi.application"


AUTH_USER_MODEL = "api.User"


db_url = os.getenv("DATABASE_URL")

if not db_url:
    raise ImproperlyConfigured("DATABASE_URL is not set!")

DATABASES = {
    "default": dj_database_url.config(
        default=db_url, conn_max_age=600, ssl_require=not DEBUG
    )
}


REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        # ── Globales ──────────────────────────────────────────────────────────
        "anon": "100/day",
        "user": "1000/day",

        # ── Auth por endpoint (independientes entre sí) ───────────────────────
        # Login: 10 intentos/hora, 30/día — bloquea fuerza bruta por IP
        "login":    "10/hour",
        # Register: 5 cuentas/hora por IP — evita spam de cuentas
        "register": "5/hour",
        # Refresh: 60/hora — el silent-refresh ocurre aprox cada expiración
        "refresh":  "60/hour",
        # Logout: 20/hora — uso legítimo máximo
        "logout":   "20/hour",

        # ── Endpoints autenticados ─────────────────────────────────────────────
        "user_me":   "70/hour",
        "burst":     "60/minute",
        "sustained": "1000/day",
        "vault":     "170/day",
        "uploads":   "350/day",

        # ── Lectura pública ───────────────────────────────────────────────────
        "public": "700/hour",
    },
}


SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=365),
    # Cada refresh genera un nuevo par de tokens y destruye el anterior.
    # Previene ataques de repetición con tokens robados.
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
    # Usa el campo UUID del modelo User como identificador dentro del token
    "USER_ID_CLAIM": "user_id",
    "USER_ID_FIELD": "id",
    # Firma con una clave JWT dedicada si está disponible, si no usa SECRET_KEY
    "SIGNING_KEY": os.getenv("JWT_SECRET_KEY", SECRET_KEY),
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "es"

LOCALE_INDEPENDENT_PATHS = True

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

LANGUAGES = [
    ("en", _("English")),
    ("es", _("Spanish")),
]

LOCALE_PATHS = [
    BASE_DIR / "locale",
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"

STATIC_ROOT = BASE_DIR / "staticfiles"



# ============================================================================
# MEDIA FILES (Imágenes, Videos, Archivos subidos por usuarios)
# ============================================================================

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# ============================================================================
# CACHÉ — Redis (producción y desarrollo con Docker)
# Fallback a LocMemCache si REDIS_URL no está definida (p.ej. tests CI sin Redis)
# ============================================================================

_REDIS_URL = os.getenv("REDIS_URL", "")

if _REDIS_URL:
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": _REDIS_URL,
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
                # Compresión automática de valores > 1KB con zlib
                "COMPRESSOR": "django_redis.compressors.zlib.ZlibCompressor",
                # Tiempo de espera para operaciones Redis
                "SOCKET_CONNECT_TIMEOUT": 5,
                "SOCKET_TIMEOUT": 5,
                # Pool de conexiones
                "CONNECTION_POOL_KWARGS": {"max_connections": 50},
                # ⚡ CLAVE: Si Redis está caído, las operaciones de caché
                # silenciosamente devuelven None en lugar de lanzar excepción.
                # El app sigue funcionando, solo sin caché (degrada con gracia).
                "IGNORE_EXCEPTIONS": True,
            },
            "KEY_PREFIX": "sumsal",
            "TIMEOUT": 300,
        }
    }
    SESSION_ENGINE = "django.contrib.sessions.backends.cached_db"
    SESSION_CACHE_ALIAS = "default"
else:
    # Sin Redis: caché en memoria por proceso (funciona en tests y CI sin Docker)
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "sumsal-locmem",
        }
    }


# ============================================================================
# SEGURIDAD HTTP — Headers de protección para la API
# ============================================================================

# Previene que el navegador adivine el tipo MIME (MIME sniffing attacks)
SECURE_CONTENT_TYPE_NOSNIFF = True

# Instruye al navegador a no renderizar esta API en un <iframe>
# (DENY es más estricto que SAMEORIGIN — no hay motivo para embeber una API)
X_FRAME_OPTIONS = "DENY"

# Referrer: envía el origen completo en peticiones al mismo dominio,
# solo el origen (sin path) en peticiones HTTPS a dominios externos,
# y nada en peticiones HTTP externas.
SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"

# En producción (detrás de Nginx con HTTPS):
# - Informar a Django que el proxy SSL está activo
# - Redirigir HTTP → HTTPS automáticamente
# - HSTS: pedirle al navegador que solo acceda por HTTPS durante 1 año
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000          # 1 año
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

if DEBUG:
    import socket
    import builtins
    from rich import print as rprint
    from rich.traceback import install

    install(show_locals=True)
    builtins.print = rprint

    if "test" not in sys.argv:
        INSTALLED_APPS += [
            "debug_toolbar",
            "django_browser_reload",
            "django_extensions",
        ]

        MIDDLEWARE = [
            "debug_toolbar.middleware.DebugToolbarMiddleware",
            "django_browser_reload.middleware.BrowserReloadMiddleware",
        ] + list(MIDDLEWARE)

    try:
        s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        s.connect(("8.8.8.8", 80))
        IP_ADDR = s.getsockname()[0]
        s.close()
    except Exception:
        IP_ADDR = "127.0.0.1"

    ALLOWED_HOSTS = ["*", "127.0.0.1", "localhost", IP_ADDR]

    CSRF_TRUSTED_ORIGINS += [f"http://{IP_ADDR}:8001"]

    CORS_ALLOW_ALL_ORIGINS = True

    # Aseguramos que CSRF confíe en tu IP local
    CSRF_TRUSTED_ORIGINS = [
        f"http://{IP_ADDR}:8001",
        "http://127.0.0.1:8001",
        "http://localhost:8001",
    ]

    print(f"React native api url: http://{IP_ADDR}:8001/api/")

    DEBUG_TOOLBAR_CONFIG = {
        "SHOW_TOOLBAR_CALLBACK": lambda request: "test" not in sys.argv,
        "IS_RUNNING_TESTS": "test" in sys.argv,
    }

    LOGGING = {
        "version": 1,
        "disable_existing_loggers": False,
        "formatters": {
            "rich": {"datefmt": "[%X]", "format": "%(message)s"},
        },
        "handlers": {
            "console": {
                "class": "rich.logging.RichHandler",
                "rich_tracebacks": True,
                "markup": True,
                "formatter": "rich",
                "tracebacks_show_locals": True,
            },
        },
        "loggers": {
            "django": {
                "handlers": ["console"],
                "level": "INFO",
                "propagate": False,
            },
            "django.server": {
                "handlers": ["console"],
                "level": "INFO",
                "propagate": False,
            },
        },
    }

    # En DEBUG se relajan los límites globales, pero se conservan los scopes
    # de autenticación para que los throttles por endpoint sigan funcionando.
    REST_FRAMEWORK["DEFAULT_THROTTLE_RATES"].update({
        "anon": "1000/day",
        "user": "5000/day",
        "auth": "100/minute",
    })


# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
